# Generated by Django 4.0.4 on 2022-05-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Наименование расхода')),
                ('category', models.CharField(max_length=200, verbose_name='Категория')),
                ('expense', models.IntegerField(verbose_name='Расход')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Коментарии')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
    ]
